extends Node

signal car_inside_car_wash
signal car_at_front_of_car_wash
signal car_cleaning_done
signal calculate_equations


signal car_created
signal car_moved_to_service
signal car_moved_to_served
